### ISSUE TITLE
VSCode: Linting in Astro Components

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#13]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

The VSCode extension doesn't provide any linting in Astro components.

### Steps to Reproduce

A custom Eslint parser should be set up for lining in the Astro components. It should have three types of linting enabled. First, for Javascript in the frontmatter. Then for HTML in the markup and for Javascript in the script tags. And then for Styling (CSS, SCSS, etc.) in the style tags. If possible, it should also have linting for Markdown inside the <kbd>Markdown</kbd> components.

**Comment by ota-meshi** [comment]
I'm experimenting with ESLint integration. If you are interested, please try it out and give me feedback.

https://github.com/ota-meshi/astro-eslint-parser

**Comment by delucis** [comment]
@ota-meshi Very cool! If you fancy chatting with people about your progress, the Astro Discord is very active: https://astro.build/chat

I’m sure people in the `#ecosystem` channel will be very excited to see this develop 😁

**Comment by Princesseuh** [comment]
Closing this since multiple things came out since the creation of this issue addressing the situation:
- TypeScript support is much much much better than it was back then, now providing pretty much all the linting you'd expect from it everywhere in the file
- ota-meshi's ESLint plugin is very good, and already in use by a lot of projects
- Since the release of the new TSX output, we now provide diagnostics from the compiler in addition to TypeScript's. This will be extended in the future to provide diagnostics similar to the Svelte's compiler (a11y, performance hints etc)

Thank you everyone!
