### ISSUE TITLE
🤝 Publish the VSCode Extension to https://open-vsx.org

### ISSUE THREAD

**Issue by jasikpark** [withastro/language-tools#16]
### Checklist

- [X] I have already searched for existing issues for this framework/library.
- [X] I have already searched npm for an existing Astro integration.
- [X] I have already tried this with Astro myself, and it did not work.

### Website or GitHub repository

https://open-vsx.org
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

### Additional Details

This should hopefully just be an update to the publishing script for the vs code extension, though that doesn't mean it won't require a bit of work.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
I'd really like to see this automated via GH actions.

**Comment by Tc-001** [comment]
There is also technically this: https://github.com/open-vsx/publish-extensions
It would mirror the extension from the marketplace, but it seems more like a "last resort" thing meant for extensions that have no chance getting published on their own

**Comment by jonathantneal** [comment]
A PR is welcome, unless this has already been accomplished. If it has, feel free to close it, @jasikpark.

**Comment by jasikpark** [comment]
Not quite yet!

**Comment by Tc-001** [comment]
I would guess someone from core has to create an account and set up the API keys. After that it should just be setting up the publish script and it all working on the first try!

**Comment by akosyakov** [comment]
Hi, Gitpod committer is here 👋 

@matthewp Unfortunately MS prohibits usages of MS marketplace by any other products or redistribution vsix files from it. Because of it we kindly ask you to take the ownership of your namespace in OpenVSX and publish there as well.

OpenVSX is a vendor neutral alternative to MS marketplace used by all other derivatives of VS Code like [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), VSCodium, Theia based IDEs, and so on.

The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: [redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82](https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82)

Let me know if you are opened to a PR contributing a release GH action both to MS marketplace and OpenVSX, similar to https://github.com/PeterWone/vsc-print/pull/121. @filiptronicek Could you provide a GH action for this repo? 🙏 

BTW at Gitpod we support open source developers by providing unlimited access to platform. Feel free to reach out via https://www.gitpod.io/docs/professional-open-source

**Comment by filiptronicek** [comment]
I am currently working on this issue and I am running into some issues, and therefore wanted to ask: how do you package up all of the 3 extensions to their respective `.vsix` files? Is there something I missed? 

cc @jonathantneal

**Comment by matthewp** [comment]
We need to claim the `astro-build` publisher. I've asked for that here: https://github.com/EclipseFdn/open-vsx.org/issues/901

Until that happens we cannot publish.

**Comment by matthewp** [comment]
Still not working :/

**Comment by filiptronicek** [comment]
@matthewp I'm sorry to see that the publishing is still not working correctly, I see there probably is an error with the namespace `astro-build`, so I see two things that potentially have happened: 
1. The token belongs to another user, because it looks like it is correct and you have claimed the ownership of the `astro-build` namespace (https://github.com/EclipseFdn/open-vsx.org/issues/901)
2. The claim for the namespace didn't go through somehow, @kineticsquid could you help here?

**Comment by matthewp** [comment]
@filiptronicek The token I used in CI was created by me. When I go to the Settings -> Namespaces page in open-vsx.org, I do not see any namespaces, so many that is the problem.

**Comment by kineticsquid** [comment]
@matthewp @filiptronicek I think this is my error. After investigating the ownership claim and finding @matthewp in the commit history, I granted the ownership request. A slip on my part as the namespace I request I granted had been claimed by `boehs`. To ensure the right transparency, let's take this discussion to the GH issue for the namespace request: https://github.com/EclipseFdn/open-vsx.org/issues/901.
