### ISSUE TITLE
🐛 BUG: CSS modules import - typescript error

### ISSUE THREAD

**Issue by KirdesMF** [withastro/language-tools#167]
### Describe the Bug

I'm actually trying to use `Astro` with `solid.js`, `css modules` for styling purpose and typescript. 

I'm facing some issues with import and autocomplete.

Actually, typescript is yelling at  me when I'm trying to import a `css module` file in a `.tsx` file

![image](https://user-images.githubusercontent.com/54989552/154814735-3befddd8-ced2-4384-9035-4f3cb60cb9f9.png)

and autocomplete does not work but I guess it's more a needed feature for me than a bug

![image](https://user-images.githubusercontent.com/54989552/154814808-5c3940f0-0860-4895-8e14-666d42a0738d.png)

and here is my `css module` file : 

![image](https://user-images.githubusercontent.com/54989552/154814842-9174d5f0-b902-4f64-81a5-e8dae8d97748.png)

Style is correctly applied to the button element :

![image](https://user-images.githubusercontent.com/54989552/154815096-6ffdd455-0f5b-4491-b689-4a99dc1c2539.png)

So to be sure, I tried in a `vite-react-ts` project, to see if I have the same import error and also to check autocomplete :

![image](https://user-images.githubusercontent.com/54989552/154815016-4c844584-7ee8-4489-be9d-c8d0f7f6ab28.png)

ts is not yelling at me :) and for autocomplete, same issue.

The actual workaround in the `astro` project, is to add a `.d.ts` file and declare css module, and ts is happy with that.

```ts
declare module "*.module.css";
```

AUTOCOMPLETE TEST :

To enable autocomplete with css module, I've found 2 solutions :

- use a vscode extension <https://marketplace.visualstudio.com/items?itemName=clinyong.vscode-css-modules>
    
    
![image](https://user-images.githubusercontent.com/54989552/154815306-9d683caa-7bab-4a96-8b84-5376d5a668ff.png)

  
- use a ts plugin `typescript-plugin-css-modules` 

```js
// tsconfig.json
"plugins": [{ "name": "typescript-plugin-css-modules" }]
```

but the problem with the plugin is that I need to toggle the ts version of vscode and use the version coming from node_modules even if there are the same

![image](https://user-images.githubusercontent.com/54989552/154815407-e7478abe-ccf4-4617-8400-8b3ef393c715.png)

In the `vite-react-ts` project, just install the plugin and toggle the ts version is enough, but in the `astro` project, I need to add typecript as peer dep

![image](https://user-images.githubusercontent.com/54989552/154815582-3b4b8bb6-3abb-4201-a4f1-30863c04df7c.png)

Astro versions tested : `0.21.12` / `0.22.20` / actual `0.23`
TS version: `4.5.5`

Hope I dont forget something important.

Edit : here is a stackblitz with my project <https://stackblitz.com/edit/github-3dfhch?file=src%2Fcomponents%2Fbutton%2FButton.tsx> but there is no error, totally lost here (:

### Steps to Reproduce

1. `pnpm init astro` 
2. choose solid.js framework
3. create a `css.module` file
4. try to import it in a component
5. TS is mad !

**Comment by KirdesMF** [comment]
Just wanted to point something out. When importing styles, vscode does not show the css file

![image](https://user-images.githubusercontent.com/54989552/154821496-3250d55a-b6c5-4080-8d4c-8b9e5d8aea1f.png)

![image](https://user-images.githubusercontent.com/54989552/154821512-9602c465-8c6c-4cd4-bf2f-1b8e282c2059.png)

**Comment by Princesseuh** [comment]
The reason this happens is because we only inject the types from `vite/client` in `.astro` files, to have it in all kinds of other files, you need to manually add `types: ['vite/client']` in your `tsconfig.json`. As [noted in Vite documentation](https://vitejs.dev/guide/features.html#client-types), `vite/client` provides types for Asset Imports (and also ImportMeta which also has the same problem where it doesn't have types in non-astro files)

There's two ways we can go on and fix this:

1. We add `types: ['vite/client']` to all the starters (and also document its need somewhere). This is a bit annoying as we'd prefer for things to work out without needing a specific config in our users projects but it would work

2. We figure out a way to inject those types in the entire workspace instead of just in `.astro` files, I'm not sure how we could go and do that yet and I'm also thinking that it might be better for this behaviour to not be so "magic"

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/astro/commit/465b3a7970c1d3e59f7aa99d68be2c8bb50547ea
