### ISSUE TITLE
🐛 BUG: Issues with `<Markdown />` components

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#249]
### Describe the Bug

I am facing some issues with the `<Markdown />` components. I am listing the issues below.

## Syntax Highlighting Issues

1. Conditionally rendered `<Markdown />` components are not highlighted.

![](https://media.discordapp.net/attachments/878341752799494154/962789628170084403/unknown.png)

2. Tags or Tag-like syntaxes breaks the syntax highlighting of the entire file (partially)

3. Backslashes of self-closing tags are highlighted with red color

![](https://media.discordapp.net/attachments/878341752799494154/962394789045735524/unknown.png)

4. Comments inside JS Objects aren't highlighted properly.

![image](https://user-images.githubusercontent.com/63650415/162756693-d3938a6a-45c2-4015-84ad-bf79be047277.png)

## Errors

1. The extension is trying to evaluate expressions inside backticks and throwing `Cannot find name "variable"` errors.

![](https://media.discordapp.net/attachments/878341752799494154/962756576635134022/unknown.png)

2. The extension is trying to find components inside code blocks and throwing errors as it is finding them `undefined`

![](https://media.discordapp.net/attachments/878341752799494154/962368372102819882/unknown.png?width=777&height=404)

### Steps to Reproduce

The extension should not throw the errors.

**Comment by Chrissdroid** [comment]
On my side, now the markdown component completly broke Highlighting when not empty

![image](https://user-images.githubusercontent.com/29927270/164039635-9f9111c3-7601-4f72-a550-5be602ac3f7e.png "Mardown breaking Syntax Highlighting with spaces as content")

![image](https://user-images.githubusercontent.com/29927270/164040109-51008fc1-307e-408a-b634-751974f06e27.png "Syntax Highlighting fixed when no content is specified in the Mardown component")

**Comment by RafidMuhymin** [comment]
@Chrissdroid do you mean when empty?

**Comment by Chrissdroid** [comment]
> @Chrissdroid do you mean when empty?

When a character is inserted between the two tags (even a space or tab character) all the syntax after the first tag are grayed out

**Comment by davidwarrington** [comment]
If it helps at all here's what I see. First, note the syntax highlighting inside the `<Fragment>` vs none inside `<Markdown>`. I assume it's because of [this change](https://github.com/withastro/language-tools/commit/9ea5b97513b132f76faffe144e75d02bc7505e54#diff-c7627d687385520ab6fcbb07973b498f140ef9cf7563780d1f3566e7ce75dc37R54).

![image](https://user-images.githubusercontent.com/9138568/164976811-bd114801-0ea6-4476-8481-c27b138c5396.png)

If I spread the content of the `Markdown` component across multiple lines the issue seems to get worse. The closing `</Markdown>` tag isn't highlighted, nor is the closing tag one level of indentation beneath.

![image](https://user-images.githubusercontent.com/9138568/164976990-441008f7-ad96-4580-bfd5-70a24ec92347.png)

![image](https://user-images.githubusercontent.com/9138568/164977075-99dc9d05-6b5b-4874-81e8-2d88078e21d0.png)

Also if I use a function inside my template VSCode reports it as being unused

![image](https://user-images.githubusercontent.com/9138568/164977248-495f359c-17f2-49ff-a365-1af6bd916816.png)

For my own purposes I can fix this by renaming the Markdown component import until this is resolved

```astro
---
import { Markdown as MD } from 'astro/components';
---

<MD>
  {page.fields.content}
</MD>
```

**Comment by Princesseuh** [comment]
Syntax parsing is exclusively done through [the syntax file](https://github.com/withastro/language-tools/blob/main/packages/vscode/syntaxes/astro.tmLanguage.json), so that changes does not impact this. It was done so TypeScript doesn't mistakenly report errors inside Markdown, which mean it also can't see what's used or not inside it. For your use case, [you should be using the content attribute](https://docs.astro.build/en/guides/markdown-content/#remote-markdown), the slot is intended to be used for writing Markdown directly (which is why it needs such special care from us 😓)

The bigger issue here is definitely a regex somewhere in the syntax file.. However, I don't plan to take a look at it for now since there's [ongoing discussions about removing the Markdown component](https://github.com/withastro/rfcs/discussions/161) 😅

**Comment by Princesseuh** [comment]
The Markdown component will be deprecated and moved to user-land in the future officially, as such, I won't be fixing the remaining (mostly syntax) issues. 

In order to make sure to properly support the coming user-land alternative, I'll be making sure we add `is:raw` support before it comes (see https://github.com/withastro/language-tools/issues/285 )

**Comment by RafidMuhymin** [comment]
@Princesseuh is it possible for the extension to provide a way to allow syntax highlighting and other features for user-land components?

**Comment by Princesseuh** [comment]
> @Princesseuh is it possible for the extension to provide a way to allow syntax highlighting and other features for user-land components?

It is technically possible however it would require knowledge of textmate scopes and would require some sort of specific syntax to inform the syntax highlighter of the scope to use for the content

If that's something we'd be interested in, we could probably have an RFC about it 

(Alternatively, it is possible to inject grammars inside our's to add support for other languages, however that would require making another VS Code extension)

**Comment by marcfilleul** [comment]
Hi,
The highlight issue is still here with the now external Markdown Component.

So I followed @davidwarrington idea by copying the Markdown.astro component from node_modules to my components folder and then renamed it to MD.astro.

Just with this new name, syntax highlighting works as expected.
But I also had to ignore this file in my prettier.ignore because formatting was ruining it.

So I was wondering if renaming the official Markdown component could be done to solve this highlight issue.
