### ISSUE TITLE
💡 RFC: Change unused variable from red to yellow

### ISSUE THREAD

**Issue by ghostdevv** [withastro/language-tools#442]
### Background & Motivation

When there is an unused variable it underlines it in red, it's confusing as that is also the colour used for errors. This makes it difficult to see at a glance whether there is an actual error or if something is just not used yet.

![image](https://user-images.githubusercontent.com/47755378/199063072-7695f22f-da1b-4b16-aa9d-df277ffd6356.png)

### Possible solutions

Make the underline yellow for unused as that information is still great to have

### Risks, downsides, and/or tradeoffs

I don't believe there are any

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Hello! This happens because you have the [`tsconfig.json` setting `noUnusedLocals`](https://www.typescriptlang.org/tsconfig#noUnusedLocals) turned on. 

This comes with the strictest preset in Astro, so perhaps you have it from there? If you disable it, you should see the same behaviour as in TypeScript files:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/3019731/199097263-37b75a89-971c-44dc-ac03-3609094f50e7.png">
