### ISSUE TITLE
🐛 BUG: `onclick` JavaScript statements are "linked"?

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/language-tools#587]
### Describe the Bug

Creating 2 HTML elements with `onclick` events can cause the first one to affect parsing of the second in VSCode. In this example, the second `onclick` attribute displays `';' expected.ts(1005)` as an error highlighting `document`.

```
<button onclick="document.querySelector('#modal').style.display='block'">Open modal</button>
<button onclick="document.querySelector('#modal').style.display='block'">Open modal</button>
```

### Steps to Reproduce

1. `npm create astro@latest -- my-app --template minimal -y`
2. Paste this code in `src/pages/index.astro` or any Astro file
```astro
<button onclick="document.querySelector('#modal').style.display='block'">Open modal</button>
<button onclick="document.querySelector('#modal').style.display='block'">Open modal</button>
```
3. `';' expected.ts(1005)` will appear as an error on line 2

**Comment by torchsmith** [comment]
Same issue here:

```
<div
	class="open"
	onclick="toggleMenu()"
>
.... bunch of html
<div
	class="open"
	onclick="toggleMenu()"
>
... bunch of html
```

**Comment by Princesseuh** [comment]
Hmm, I definitely get why this happens (All the inline scripts are technically in one file that get type checked, since they operate in the same scope), to which a simple partial solution is to append a virtual semi-colons at the end of every context, however that would still cause some errors to spill over, I wonder how VS Code avoids this in their HTML support. Will have to investigate, funny one
