### ISSUE TITLE
🐛 BUG: External modules exporting *.astro files aren't detected anymore using intellisense.

### ISSUE THREAD

**Issue by piratey7007** [withastro/language-tools#609]
### Describe the Bug

Any *.astro files from node_modules, even the built-in `astro` package, aren't detected anymore in the language-tools v2.1.1. In previous versions of the language-tools plugin, these were visible when importing, and error-free. Is this an intended feature or known side-effect?

### Steps to Reproduce

1. `npm init astro`.
2. Make sure you're using the Astro language-tools plugin v2.1.1 (latest version).
3. Type `import Code from "astro/components/Code.astro";` (or any other *.astro file from node_modules).
5. Error: `Cannot find module 'astro/components/Code.astro' or its corresponding type declarations.`
6. Try these steps again in v2.0.18 (and reload VSCode) and you will notice that it works.

**Comment by johnsoncodehk** [comment]
This is a side effect of Volar.js 1.9, some people are experiencing huge memory increases due to auto-parsing .astro/.vue files outside the root path, so we currently have auto-parsing external files disabled, but looking for a solution.

You can add `node_modules/your_pkg/**/*.astro` to tsconfig include option as a temporary solution. (I also recommend you to use https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper to visualize it.)

**Comment by piratey7007** [comment]
@johnsoncodehk Thank you very much for getting back to me so quickly. I'll either do that or downgrade for the time being.

**Comment by johnsoncodehk** [comment]
No problem, let's keep this issue open to track upstream fixes. 👌

**Comment by Princesseuh** [comment]
This should be fixed as of 2.1.3.
