### ISSUE TITLE
🐛 BUG: Syntax highlighting in braces

### ISSUE THREAD

**Issue by cdtut** [withastro/language-tools#714]
### Describe the Bug

Words inside braces have wrong highlighting. They are different from same words outside braces.

### Steps to Reproduce

Write in vscode and see highlighting.

```
<div>word</div>
{true && <div>word</div>}
```

**Comment by cdtut** [comment]
If theme doesn't define `text.astro` I can override it in settings file to color in different way?

**Comment by cdtut** [comment]
Inspect Editor Tokens and Scopes for background show:

```
meta.jsx.children.tsx
meta.tag.tsx
meta.jsx.children.tsx
meta.tag.without-attributes.tsx
meta.jsx.children.tsx
meta.tag.without-attributes.tsx
meta.arrow.tsx
source.tsx
meta.embedded.expression.astro
source.astro
```

And foreground:

```
meta.tag
```

Overriding `text.astro` or `source.astro` change the color of word in `<div>word</div>` but not `{true && <div>word</div>}`.

**Comment by Princesseuh** [comment]
We could probably set `meta.tag` on the content of the tag like JSX does, yes! We followed HTML in this regard where the content is always `text`.

Would you be willing to send a PR for this? I can't quite remember how we handle tag content so can't pinpoint the line just now, but the syntax file is here and should be fairly documented: https://github.com/withastro/language-tools/blob/main/packages/vscode/syntaxes/astro.tmLanguage.src.yaml

**Comment by goulvenclech** [comment]
Sadly @cdtut , HTML and JSX have different approaches to syntax highlighting. JSX choose to have a pattern `meta.tag` matching tags (start and end) and their content, while HTML chooses to differentiate tags and text (tags content). 

Astro chose to follow HTML, and it seems impossible to make these philosophies coexist 😕 @Princesseuh maybe you should close this issue?

**Comment by Princesseuh** [comment]
Yeah, after investigating it seems like it's impossible to make everything work. You end up either breaking themes that highlight JSX's `meta.tag` a particular way, or you break those that highlight `text` a particular way. It's quite wonky. Other frameworks that uses JavaScript's TextMate grammar + HTML also have a similar issue.

Since:
- There's a workaround
- It doesn't affect a lot of themes
- We generally align with HTML when possible

I'll just close this, apologies for the inconveniences. In the future, if we choose the completely own syntax highlighting inside expressions, we could fix this then, but it's a fairly consequential task.
