### ISSUE TITLE
🐛 BUG: Support for typescript inside <script> tags with define:vars

### ISSUE THREAD

**Issue by calvinrbnspiess** [withastro/language-tools#755]
### Describe the Bug

Hello! I'm currently experiencing the following issue. When using the astro language tools inside VS Code, I'm getting typescript errors like "_Type assertion expressions can only be used in TypeScript files.ts(8016)_".

Generally the typ checking is working flawlessly, however this odd error appears when I'm adding the `define:vars` property.

The lack for define:vars is mentioned inside this pull request: https://github.com/withastro/language-tools/pull/263

Is this behaviour still intentional? Are there any workarounds till this gets fixed?

**This is working:**

<img width="598" alt="Bildschirmfoto 2024-01-11 um 16 25 57" src="https://github.com/withastro/language-tools/assets/5459550/51036666-7596-47e5-9dcc-07005f4726bc">

**This is not working:**

<img width="1023" alt="Bildschirmfoto 2024-01-11 um 16 25 40" src="https://github.com/withastro/language-tools/assets/5459550/8739064e-8470-4f51-ad26-b96182c89c55">

My `tscconfig.json`:

```
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  }
}
```

Extension (astro-build.astro-vscode) version: v2.6.2
VS Code version: 1.85.1 (Universal)

```
    "astro": "^4.0.2",
    "@astrojs/check": "^0.3.1",
    "@astrojs/react": "^3.0.9",
    "@astrojs/tailwind": "^5.0.3",
    "typescript": "^5.3.2"
```

### Steps to Reproduce

1. Write typescript annotations inside a script tag in an astro codebase.
2. Add `define:vars={{ title: "test " }}`

**Comment by calvinrbnspiess** [comment]
After further reading I discovered, that is behaviour is intentional. Whenever someone defines the property `define:vars` on a script tag, it will inherit the `is:inline` directive as stated in the big yellow warning on this docs page: https://docs.astro.build/en/reference/directives-reference/#definevars

Inline script won't be bundled and won't be processed by typescript, sadly.

**Comment by sommerper** [comment]
Would be nice if that could get added. I've had to remove the types so many times now because I at some point realize that I need `define:vars`.

At this point I'm considering to just not use typescript. But I would honestly prefer that typescript would be transpiled also when it inline.

**Comment by bigrand** [comment]
If anyone needs to pass a frontmatter variable to a script but wants to use TypeScript, it's possible.

All you need to do is store your variable in a `data-` attribute. Personally, I use a hidden, empty div. In my case, what I wanted to do is pass an array of objects, so I had to convert it to JSON because HTML attributes can only store string values.
```html
<div data-checklist={JSON.stringify(checklistProgression)} hidden></div>
```

Then, in the script, I selected it, parsed it, and stored it in a variable.
```typescript
const checklistProgression = JSON.parse(
    (document.querySelector('[data-checklist]') as HTMLElement).dataset.checklist!
);
```

The type assertion is necessary to expose `.dataset`, and the `!` is used to tell TypeScript that the property definitely exists, so it doesn't raise an error about potential null or undefined values.

This is explained in the [docs](https://docs.astro.build/en/guides/client-side-scripts/#pass-frontmatter-variables-to-scripts).
